"""
=============================================================================
Script 01 — Quality Control and Cell Filtering
=============================================================================
Project : RetinoblastomaAtlas
Author  : Md. Jubayer Hossain
Date    : 2026-04-29

WHY THIS ANALYSIS?
------------------
Single-cell RNA-seq data contain a mixture of high-quality cells and technical
artifacts that must be removed before any biological interpretation. The three
principal artifact classes are:

  1. **Dead / dying cells** — characterised by high mitochondrial gene fraction
     (mt%) because cytoplasmic mRNA is lost through damaged membranes while
     mitochondrial mRNA is retained.  Inclusion of dying cells inflates
     technical variance and masks real cell-type differences.

  2. **Empty droplets / ambient RNA** — GEMs (gel-bead-in-emulsions) that
     captured no real cell but contain floating mRNA from the solution.
     These appear as cells with very low UMI counts.  SoupX corrects the
     ambient contamination per sample (Young & Behjati, 2020).

  3. **Doublets** — two cells captured in the same GEM, mis-identified as one
     high-count cell.  In retinoblastoma data, doublets create spurious
     "hybrid" populations that could be misannotated as transitional states —
     directly confounding the cone precursor trajectory analysis (Aim 3).
     Scrublet detects doublets via nearest-neighbour simulation (Wolock et al.,
     2019).

SIGNIFICANCE IN THIS PROJECT
-----------------------------
Retinoblastoma is a rare tumour with limited tissue availability.  Every
post-QC cell lost to a loose threshold is irreplaceable; every artefact
retained contaminates the batch-correction latent space.  The per-sample
adaptive thresholding strategy (MAD-based outlier detection) used here is
preferable to fixed cut-offs because it accommodates the different sequencing
depths and cell compositions between GSE168434 (7 patients) and GSE249995
(4 samples), which were generated by different laboratories.

REFERENCES
----------
- Young MD, Behjati S. SoupX removes ambient RNA contamination from
  droplet-based single-cell RNA sequencing data.
  GigaScience. 2020;9(12):giaa151.
  https://doi.org/10.1093/gigascience/giaa151

- Wolock SL, Lopez R, Klein AM. Scrublet: Computational identification of
  cell doublets in single-cell transcriptomic data.
  Cell Syst. 2019;8(4):281-291.e9.
  https://doi.org/10.1016/j.cels.2018.11.005

- Wolf FA, Angerer P, Theis FJ. SCANPY: large-scale single-cell gene
  expression data analysis. Genome Biol. 2018;19:15.
  https://doi.org/10.1186/s13059-017-1382-0

INPUT
-----
  data/processed/merged_raw_atlas.h5ad
    AnnData produced by 01-data-preprocessing.ipynb.
    .X  : raw UMI counts (int)
    .obs : sample_id, dataset columns

OUTPUT
------
  data/processed/02_qc_filtered.h5ad
    AnnData of cells passing QC; raw counts in .layers['counts']
  results/tables/qc_metrics_per_cell.csv
  results/tables/qc_summary_per_sample.csv
  results/figures/qc_violin_per_sample.pdf
  results/figures/qc_scatter_mt_vs_counts.pdf
  results/figures/doublet_scores_histogram.pdf

USAGE
-----
  pixi run python script/01_qc_filtering.py
  pixi run python script/01_qc_filtering.py --mt-threshold 25 --min-genes 500
=============================================================================
"""

from __future__ import annotations

import argparse
import logging
import sys
import warnings
from pathlib import Path

import matplotlib
matplotlib.use("Agg")                       # non-interactive backend for WSL2
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scanpy as sc
import scrublet as scr
from scipy.sparse import issparse

# ---------------------------------------------------------------------------
# Paths (relative to project root; script is invoked from project root)
# ---------------------------------------------------------------------------
ROOT        = Path(__file__).resolve().parents[1]
IN_H5AD     = ROOT / "data" / "processed" / "01_merged_raw.h5ad"
OUT_H5AD    = ROOT / "data" / "processed" / "02_qc_filtered.h5ad"
FIG_DIR     = ROOT / "results" / "figures"
TAB_DIR     = ROOT / "results" / "tables"

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
log = logging.getLogger(__name__)

warnings.filterwarnings("ignore", category=FutureWarning)
sc.settings.verbosity = 1


# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

def mad_threshold(series: pd.Series, n_mads: float = 5.0) -> tuple[float, float]:
    """Compute symmetric MAD-based outlier thresholds.

    Using the Median Absolute Deviation (MAD) rather than mean ± n*SD is
    robust to the heavy tails typical of scRNA-seq count distributions.
    A cell is considered an outlier if its metric is more than `n_mads`
    MADs from the sample median.

    Parameters
    ----------
    series : per-cell QC values for ONE sample
    n_mads : number of MADs defining the outlier band (default 5)

    Returns
    -------
    (lower_bound, upper_bound)
    """
    median = np.median(series)
    mad    = np.median(np.abs(series - median))
    return median - n_mads * mad, median + n_mads * mad


def run_scrublet(
    adata_sample: sc.AnnData,
    sample_id: str,
    expected_doublet_rate: float = 0.06,
    threshold: float = 0.25,
) -> pd.Series:
    """Run Scrublet on a single sample and return per-cell doublet scores.

    WHY PER-SAMPLE?
    Scrublet simulates doublets by combining pairs of observed cells.
    If run on the merged atlas, the expected doublet neighbourhood is
    dominated by the most abundant cell types and the per-sample expected
    doublet rate (which depends on loading density) cannot be set correctly.
    Running per-sample avoids both issues.

    Parameters
    ----------
    adata_sample : AnnData for a single sample (raw counts)
    sample_id    : label used in log messages
    expected_doublet_rate : 10x Chromium v3 ≈ 0.8% per 1000 cells loaded.
                            GEMs loaded at ~5000 cells ≈ 4–6% doublets.
    threshold    : Scrublet score above which a cell is called a doublet

    Returns
    -------
    pd.Series (index = cell barcode) of doublet scores
    """
    log.info(f"  Scrublet: {sample_id} — {adata_sample.n_obs:,} cells")
    counts = adata_sample.X
    if issparse(counts):
        counts = counts.toarray()

    scrub = scr.Scrublet(counts, expected_doublet_rate=expected_doublet_rate)
    doublet_scores, predicted_doublets = scrub.scrub_doublets(
        min_counts=2, min_cells=3, n_prin_comps=30, verbose=False
    )
    # If automatic threshold is very low, override with manual threshold
    if scrub.threshold_ < 0.15:
        log.warning(
            f"  Scrublet threshold {scrub.threshold_:.3f} very low for "
            f"{sample_id}; using manual threshold {threshold}"
        )
        predicted_doublets = doublet_scores >= threshold

    n_doublets = predicted_doublets.sum()
    log.info(
        f"  {sample_id}: {n_doublets} doublets ({100*n_doublets/len(doublet_scores):.1f}%)"
    )
    return pd.Series(doublet_scores, index=adata_sample.obs_names, name="doublet_score"), \
           pd.Series(predicted_doublets, index=adata_sample.obs_names, name="is_doublet")


def plot_qc_violins(adata: sc.AnnData, out_path: Path) -> None:
    """Per-sample violin plots for nGenes, nCounts, mt%.

    SIGNIFICANCE:
    Visualising QC distributions per sample reveals whether batch effects
    are driven by technical differences in sequencing depth or cell viability
    rather than biological variation — critical for interpreting the
    subsequent scVI correction.
    """
    fig, axes = plt.subplots(3, 1, figsize=(14, 12))
    metrics = [
        ("n_genes_by_counts", "Genes detected per cell"),
        ("total_counts",      "Total UMI counts per cell"),
        ("pct_counts_mt",     "Mitochondrial gene fraction (%)"),
    ]
    for ax, (metric, title) in zip(axes, metrics):
        sc.pl.violin(
            adata, metric, groupby="sample_id",
            rotation=45, show=False, ax=ax, size=0.3,
        )
        ax.set_title(title, fontsize=11, fontweight="bold")
        ax.set_xlabel("")
    plt.tight_layout()
    fig.savefig(out_path, dpi=200, bbox_inches="tight")
    plt.close(fig)
    log.info(f"  Saved: {out_path.name}")


def plot_mt_scatter(adata: sc.AnnData, out_path: Path) -> None:
    """Scatter plot: total counts vs mt% coloured by sample.

    SIGNIFICANCE:
    The classic 'hockey stick' pattern (high mt% at low counts) confirms
    that dying cells are being correctly identified.  Cells diverging
    from this pattern at high counts are suspicious for doublets or highly
    metabolically active cell types (e.g., activated macrophages) and
    inform threshold refinement.
    """
    fig, ax = plt.subplots(figsize=(8, 6))
    samples  = adata.obs["sample_id"].cat.categories
    palette  = plt.cm.tab20(np.linspace(0, 1, len(samples)))
    for sample, color in zip(samples, palette):
        mask = adata.obs["sample_id"] == sample
        ax.scatter(
            adata.obs.loc[mask, "total_counts"],
            adata.obs.loc[mask, "pct_counts_mt"],
            s=1, alpha=0.3, color=color, label=sample, rasterized=True,
        )
    ax.set_xlabel("Total UMI counts (log scale)", fontsize=11)
    ax.set_ylabel("Mitochondrial %", fontsize=11)
    ax.set_xscale("log")
    ax.legend(bbox_to_anchor=(1.02, 1), loc="upper left", markerscale=5,
              fontsize=7, frameon=False)
    ax.set_title(
        "QC scatter: total counts vs mitochondrial fraction\n"
        "(high mt% at low counts = dying cells)",
        fontsize=10,
    )
    plt.tight_layout()
    fig.savefig(out_path, dpi=200, bbox_inches="tight")
    plt.close(fig)
    log.info(f"  Saved: {out_path.name}")


def plot_doublet_histogram(adata: sc.AnnData, out_path: Path) -> None:
    """Histogram of Scrublet scores coloured by predicted doublet status.

    SIGNIFICANCE:
    A well-calibrated Scrublet run produces a bimodal distribution: a
    singlet peak near 0 and a doublet peak at higher scores.  Absence of
    bimodality may indicate that the expected doublet rate parameter
    needs adjustment.
    """
    fig, ax = plt.subplots(figsize=(8, 5))
    doublets  = adata.obs["doublet_score"][adata.obs["is_doublet"]  == True]
    singlets  = adata.obs["doublet_score"][adata.obs["is_doublet"] == False]
    ax.hist(singlets, bins=100, alpha=0.7, color="#4C9BE8", label="Singlet")
    ax.hist(doublets, bins=100, alpha=0.7, color="#E84C4C", label="Doublet")
    ax.set_xlabel("Scrublet doublet score", fontsize=11)
    ax.set_ylabel("Number of cells", fontsize=11)
    ax.set_title("Doublet score distribution (Scrublet)", fontsize=11)
    ax.legend(fontsize=10)
    plt.tight_layout()
    fig.savefig(out_path, dpi=200, bbox_inches="tight")
    plt.close(fig)
    log.info(f"  Saved: {out_path.name}")


# ---------------------------------------------------------------------------
# Main QC pipeline
# ---------------------------------------------------------------------------

def run_qc(
    mt_threshold: float = 20.0,
    min_genes: int = 300,
    min_counts: int = 500,
    n_mads: float = 5.0,
    doublet_threshold: float = 0.25,
) -> sc.AnnData:
    """Full QC pipeline.

    Steps
    -----
    1. Load merged raw atlas.
    2. Annotate mitochondrial genes.
       WHY: Mitochondrial transcripts (gene names starting with 'MT-') are
       encoded in the mitochondrial genome. Their fraction is the primary
       proxy for cell viability — dead cells lose cytoplasmic mRNA faster
       than mitochondrial mRNA, so the MT fraction rises as a cell dies.
    3. Compute per-cell QC metrics (Scanpy).
    4. Run Scrublet per sample to score doublets.
    5. Apply MAD-based per-sample filters on nGenes and nCounts.
    6. Apply a global mt% threshold (20% is permissive enough for activated
       immune cells while capturing obvious dead cells).
    7. Remove predicted doublets.
    8. Save QC statistics and filtered AnnData.
    """
    # ---- 1. Load --------------------------------------------------------
    log.info("=" * 60)
    log.info("STEP 1 — Loading merged raw atlas")
    log.info("=" * 60)
    adata = sc.read_h5ad(IN_H5AD)
    log.info(f"  Loaded: {adata.n_obs:,} cells × {adata.n_vars:,} genes")
    log.info(f"  Samples: {adata.obs['sample_id'].nunique()}")
    log.info(f"  Datasets: {adata.obs['dataset'].value_counts().to_dict()}")

    # ---- 2. Annotate mitochondrial genes --------------------------------
    log.info("\nSTEP 2 — Annotating mitochondrial genes")
    adata.var["mt"] = adata.var_names.str.startswith("MT-")
    n_mt = adata.var["mt"].sum()
    log.info(f"  Found {n_mt} mitochondrial genes")

    # ---- 3. QC metrics --------------------------------------------------
    log.info("\nSTEP 3 — Computing per-cell QC metrics")
    sc.pp.calculate_qc_metrics(
        adata,
        qc_vars=["mt"],
        percent_top=None,
        log1p=False,
        inplace=True,
    )
    # Save raw QC table before filtering
    qc_df = adata.obs[
        ["sample_id", "dataset", "n_genes_by_counts", "total_counts", "pct_counts_mt"]
    ].copy()
    qc_df.to_csv(TAB_DIR / "qc_metrics_per_cell_raw.csv")
    log.info(
        f"  Median genes/cell: {adata.obs['n_genes_by_counts'].median():.0f}\n"
        f"  Median counts/cell: {adata.obs['total_counts'].median():.0f}\n"
        f"  Median mt%: {adata.obs['pct_counts_mt'].median():.1f}%"
    )

    # ---- Plot before filtering ------------------------------------------
    plot_qc_violins(adata, FIG_DIR / "qc_violin_before_filter.pdf")
    plot_mt_scatter(adata, FIG_DIR / "qc_scatter_mt_vs_counts.pdf")

    # ---- 4. Doublet detection per sample --------------------------------
    log.info("\nSTEP 4 — Doublet detection (Scrublet, per sample)")
    log.info(
        "  WHY PER-SAMPLE: Scrublet simulates doublets by pairing cells;\n"
        "  running on the full merged atlas mixes doublet rates across\n"
        "  samples, which were loaded at different densities."
    )
    all_scores  = []
    all_predict = []
    for sid in adata.obs["sample_id"].cat.categories:
        mask = adata.obs["sample_id"] == sid
        scores, predicted = run_scrublet(
            adata[mask].copy(), sid, threshold=doublet_threshold
        )
        all_scores.append(scores)
        all_predict.append(predicted)

    adata.obs["doublet_score"] = pd.concat(all_scores).reindex(adata.obs_names)
    adata.obs["is_doublet"]    = pd.concat(all_predict).reindex(adata.obs_names)

    n_doublets = adata.obs["is_doublet"].sum()
    log.info(
        f"  Total predicted doublets: {n_doublets:,} "
        f"({100*n_doublets/adata.n_obs:.1f}% of all cells)"
    )

    plot_doublet_histogram(adata, FIG_DIR / "doublet_scores_histogram.pdf")

    # ---- 5. Per-sample MAD filtering ------------------------------------
    log.info("\nSTEP 5 — Per-sample MAD-based outlier filtering")
    log.info(
        f"  Using {n_mads} MADs; hard lower bounds: "
        f"min_genes={min_genes}, min_counts={min_counts}"
    )
    keep_mask = pd.Series(True, index=adata.obs_names)
    summary_rows = []

    for sid in adata.obs["sample_id"].cat.categories:
        mask = adata.obs["sample_id"] == sid
        sub  = adata.obs.loc[mask]

        lo_g, hi_g = mad_threshold(sub["n_genes_by_counts"], n_mads)
        lo_c, hi_c = mad_threshold(sub["total_counts"],      n_mads)

        lo_g = max(lo_g, min_genes)
        lo_c = max(lo_c, min_counts)

        bad = (
            (sub["n_genes_by_counts"] < lo_g) |
            (sub["n_genes_by_counts"] > hi_g) |
            (sub["total_counts"]      < lo_c) |
            (sub["total_counts"]      > hi_c)
        )
        keep_mask.loc[sub.index[bad]] = False
        summary_rows.append({
            "sample_id": sid,
            "n_cells_before": mask.sum(),
            "lo_genes": lo_g, "hi_genes": hi_g,
            "lo_counts": lo_c, "hi_counts": hi_c,
            "cells_failed_count_filter": int(bad.sum()),
        })
        log.info(
            f"  {sid}: genes [{lo_g:.0f}, {hi_g:.0f}], "
            f"counts [{lo_c:.0f}, {hi_c:.0f}] → removed {bad.sum()} cells"
        )

    # ---- 6. Global mt% filter -------------------------------------------
    log.info(f"\nSTEP 6 — Global mitochondrial filter: mt% < {mt_threshold}%")
    high_mt = adata.obs["pct_counts_mt"] >= mt_threshold
    log.info(f"  Cells with mt% ≥ {mt_threshold}: {high_mt.sum():,}")
    keep_mask = keep_mask & (~high_mt)

    # ---- 7. Remove doublets ---------------------------------------------
    log.info("\nSTEP 7 — Removing predicted doublets")
    keep_mask = keep_mask & (~adata.obs["is_doublet"].astype(bool))

    # ---- Apply filters --------------------------------------------------
    adata_filt = adata[keep_mask].copy()
    n_removed  = adata.n_obs - adata_filt.n_obs
    log.info(
        f"\n{'=' * 60}\n"
        f"  Cells before QC : {adata.n_obs:>8,}\n"
        f"  Cells removed   : {n_removed:>8,} ({100*n_removed/adata.n_obs:.1f}%)\n"
        f"  Cells retained  : {adata_filt.n_obs:>8,}\n"
        f"{'=' * 60}"
    )

    # ---- Remove genes expressed in <20 cells ----------------------------
    log.info("\nSTEP 7b — Removing lowly expressed genes")
    sc.pp.filter_genes(adata_filt, min_cells=20)
    log.info(f"  Genes retained: {adata_filt.n_vars:,}")

    # ---- Preserve raw counts layer for scVI ----------------------------
    log.info("\nSTEP 8 — Storing raw counts in .layers['counts']")
    log.info(
        "  WHY: scVI (script 03) requires integer raw counts as input.\n"
        "  We store them here before any normalisation so they survive\n"
        "  downstream .X modifications."
    )
    adata_filt.layers["counts"] = adata_filt.X.copy()

    # ---- Post-filter QC violin -----------------------------------------
    plot_qc_violins(adata_filt, FIG_DIR / "qc_violin_after_filter.pdf")

    # ---- Summary table --------------------------------------------------
    summary_df = pd.DataFrame(summary_rows)
    summary_df.to_csv(TAB_DIR / "qc_summary_per_sample.csv", index=False)
    log.info(f"\n  Saved summary table: {TAB_DIR / 'qc_summary_per_sample.csv'}")

    # ---- Save ----------------------------------------------------------
    log.info(f"\nSTEP 9 — Saving filtered AnnData → {OUT_H5AD.name}")
    adata_filt.write_h5ad(OUT_H5AD, compression="gzip")
    log.info("  Done.")

    return adata_filt


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Quality control and cell filtering for RetinoblastomaAtlas",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--mt-threshold",      type=float, default=20.0,
                   help="Maximum mitochondrial %% allowed per cell")
    p.add_argument("--min-genes",         type=int,   default=300,
                   help="Hard lower bound on genes detected per cell")
    p.add_argument("--min-counts",        type=int,   default=500,
                   help="Hard lower bound on UMI counts per cell")
    p.add_argument("--n-mads",            type=float, default=5.0,
                   help="Number of MADs for per-sample outlier detection")
    p.add_argument("--doublet-threshold", type=float, default=0.25,
                   help="Scrublet score threshold above which a cell is a doublet")
    return p.parse_args()


if __name__ == "__main__":
    args = parse_args()
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    TAB_DIR.mkdir(parents=True, exist_ok=True)

    run_qc(
        mt_threshold      = args.mt_threshold,
        min_genes         = args.min_genes,
        min_counts        = args.min_counts,
        n_mads            = args.n_mads,
        doublet_threshold = args.doublet_threshold,
    )
