"""
=============================================================================
Script 03 — scVI Batch Correction and Atlas Integration
=============================================================================
Project : RetinoblastomaAtlas
Author  : Md. Jubayer Hossain
Date    : 2026-04-29

WHY THIS ANALYSIS?
------------------
The two GEO datasets (GSE168434 and GSE249995) were generated by different
research groups, with different 10x Genomics kit versions, cDNA capture
efficiencies, and sequencing depths. Naively combining them without batch
correction would result in cells clustering by dataset origin rather than
by biology — making it impossible to jointly annotate cell types or compare
intraocular vs. extraocular states.

WHY scVI OVER LINEAR METHODS?
------------------------------
Classical batch correction methods (ComBat, Harmony) model technical
effects as linear additive or multiplicative corrections to log-normalized
expression values. scRNA-seq count data is fundamentally *non-Gaussian and
non-linear*: it follows a negative binomial distribution with gene-specific
dispersion parameters. scVI (Single-Cell Variational Inference, Lopez et al.
2018) addresses this by:

  1. Modelling raw counts directly through a negative binomial decoder,
     preserving the count-level statistical properties.
  2. Learning a *latent representation* (30-dimensional) in which biological
     variation is encoded and batch effects are modelled as explicit
     conditioning variables.
  3. Returning a batch-corrected gene expression matrix (scVI-normalized) for
     visualization and a latent embedding for neighbour-graph construction.

In practice, scVI-corrected atlases of paediatric tumours have shown superior
cell-type clustering consistency compared to Harmony or Seurat integration,
as benchmarked by the scib suite (Luecken et al. 2022).

SIGNIFICANCE IN THIS PROJECT
-----------------------------
Correct batch integration is the *foundation* of every downstream analysis
aim:
  - Aim 2 (annotation) requires that intraocular and extraocular cells of
    the same type cluster together.
  - Aim 3 (RNA velocity) requires that cone precursor subclusters from both
    datasets are properly co-embedded.
  - Aim 4 (CellChat) requires that TME cells from GSE168434 and GSE249995
    are jointly characterized.

INTEGRATION QUALITY METRICS (scib)
------------------------------------
After training, we evaluate integration quality with two competing objectives:
  - Batch correction:  iLISI, kBET, graph connectivity
  - Biological conservation: cLISI, NMI, ARI
A good integration maximises both — this is the 'overall' scib score.
The target is an overall score > 0.7 (Luecken et al. 2022).

REFERENCES
----------
- Lopez R et al. Deep generative modeling for single-cell transcriptomics.
  Nat Methods. 2018;15(12):1053-1058.
  https://doi.org/10.1038/s41592-018-0229-2

- Luecken MD et al. Benchmarking atlas-level data integration in
  single-cell genomics. Nat Methods. 2022;19(1):41-50.
  https://doi.org/10.1038/s41592-021-01336-8

INPUT  : data/processed/03_normalized.h5ad
OUTPUT :
  data/processed/04_scvi_integrated.h5ad
  results/figures/umap_before_integration.pdf
  results/figures/umap_after_integration_dataset.pdf
  results/figures/umap_after_integration_sample.pdf
  results/figures/scvi_training_history.pdf
  results/tables/scib_integration_metrics.csv

USAGE  : pixi run python script/03_scvi_integration.py [--n-latent 30]
=============================================================================
"""

from __future__ import annotations

import argparse
import logging
import sys
import warnings
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scanpy as sc
import scvi

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
ROOT     = Path(__file__).resolve().parents[1]
IN_H5AD  = ROOT / "data" / "processed" / "03_normalized.h5ad"
OUT_H5AD = ROOT / "data" / "processed" / "04_scvi_integrated.h5ad"
MODEL_DIR = ROOT / "data" / "processed" / "scvi_model"
FIG_DIR  = ROOT / "results" / "figures"
TAB_DIR  = ROOT / "results" / "tables"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
log = logging.getLogger(__name__)
warnings.filterwarnings("ignore")
sc.settings.verbosity = 1
scvi.settings.verbosity = 1


# ---------------------------------------------------------------------------
# Plotting helpers
# ---------------------------------------------------------------------------

def plot_umap(
    adata: sc.AnnData,
    color_keys: list[str],
    title: str,
    out_path: Path,
    use_rep: str = "X_umap",
) -> None:
    """Publication-ready UMAP coloured by multiple keys."""
    ncols = len(color_keys)
    fig, axes = plt.subplots(1, ncols, figsize=(6 * ncols, 5))
    if ncols == 1:
        axes = [axes]
    for ax, key in zip(axes, color_keys):
        sc.pl.umap(adata, color=key, ax=ax, show=False, frameon=False,
                   size=2, alpha=0.7)
        ax.set_title(key, fontsize=11)
    plt.suptitle(title, fontsize=12, fontweight="bold", y=1.02)
    plt.tight_layout()
    fig.savefig(out_path, dpi=200, bbox_inches="tight")
    plt.close(fig)
    log.info(f"  Saved: {out_path.name}")


def plot_training_history(history: dict, out_path: Path) -> None:
    """Plot scVI training loss curve.

    SIGNIFICANCE:
    Convergence of the ELBO (Evidence Lower BOund) loss confirms that the
    variational autoencoder has reached a stable minimum.  A still-decreasing
    loss at max_epochs would indicate under-training; a loss that diverges
    indicates numerical instability (usually fixed by reducing learning rate).
    """
    train_loss = history.get("train_loss_epoch", [])
    val_loss   = history.get("elbo_validation",  [])
    fig, ax = plt.subplots(figsize=(8, 5))
    if train_loss:
        ax.plot(train_loss, label="Training ELBO", color="#4C9BE8")
    if val_loss:
        ax.plot(val_loss,   label="Validation ELBO", color="#E84C4C",
                linestyle="--")
    ax.set_xlabel("Epoch", fontsize=11)
    ax.set_ylabel("ELBO loss", fontsize=11)
    ax.set_title("scVI training history\n(lower = better)", fontsize=11)
    ax.legend(fontsize=10)
    plt.tight_layout()
    fig.savefig(out_path, dpi=200, bbox_inches="tight")
    plt.close(fig)
    log.info(f"  Saved: {out_path.name}")


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

def run_integration(
    n_latent: int  = 30,
    n_layers: int  = 2,
    n_hidden: int  = 128,
    max_epochs: int = 400,
    lr: float      = 1e-3,
    leiden_resolutions: list = (0.3, 0.5, 1.0),
) -> sc.AnnData:
    """scVI integration pipeline.

    Steps
    -----
    1. Load normalized atlas.
    2. Visualise pre-integration UMAP (batch effect diagnostic).
    3. Set up scVI model on raw counts with batch covariate.
    4. Train scVI (VAE with negative binomial decoder).
    5. Extract latent representation and compute batch-corrected expression.
    6. Build neighbour graph on latent embedding.
    7. UMAP and Leiden clustering.
    8. Evaluate integration quality (scib-metrics).
    9. Save integrated atlas and trained model.
    """

    # ---- 1. Load --------------------------------------------------------
    log.info("=" * 60)
    log.info("STEP 1 — Loading normalized atlas")
    log.info("=" * 60)
    adata = sc.read_h5ad(IN_H5AD)
    log.info(f"  {adata.n_obs:,} cells × {adata.n_vars:,} genes")

    # ---- 2. Pre-integration UMAP (diagnostic) ---------------------------
    log.info("\nSTEP 2 — Pre-integration UMAP (batch effect diagnosis)")
    log.info(
        "  WHY: Computing UMAP on the un-corrected PCA space shows how\n"
        "  severe the batch effect is. Cells that cluster by dataset\n"
        "  instead of cell type confirm the need for batch correction."
    )
    sc.pp.neighbors(adata, use_rep="X_pca_pre_scvi", n_neighbors=30, n_pcs=30)
    sc.tl.umap(adata, min_dist=0.3)
    adata.obsm["X_umap_pre_scvi"] = adata.obsm["X_umap"].copy()
    plot_umap(
        adata, ["dataset", "sample_id"],
        "UMAP before scVI integration",
        FIG_DIR / "umap_before_integration.pdf",
    )

    # ---- 3. scVI model setup --------------------------------------------
    log.info("\nSTEP 3 — Setting up scVI model")
    log.info(
        f"  Architecture: {n_layers} encoder/decoder layers, "
        f"{n_hidden} hidden units, {n_latent}-d latent space\n"
        "  Gene likelihood: Negative Binomial (accounts for overdispersion\n"
        "  of scRNA-seq counts; superior to Poisson or Gaussian)\n"
        "  Batch key: 'dataset' (GSE168434 vs. GSE249995)\n"
        "  Categorical covariate: 'sample_id' (individual patient)\n"
        "  Continuous covariate: 'pct_counts_mt' (residual technical signal)"
    )
    # scVI requires raw integer counts
    scvi.model.SCVI.setup_anndata(
        adata,
        layer="counts",
        batch_key="dataset",
        categorical_covariate_keys=["sample_id"],
        continuous_covariate_keys=["pct_counts_mt"],
    )
    model = scvi.model.SCVI(
        adata,
        n_latent=n_latent,
        n_layers=n_layers,
        n_hidden=n_hidden,
        gene_likelihood="nb",         # negative binomial decoder
        dispersion="gene-batch",      # per-gene, per-batch dispersion estimate
        use_layer_norm="both",
        use_batch_norm="none",
    )
    log.info(f"  Model summary:\n{model}")

    # ---- 4. Train scVI --------------------------------------------------
    log.info(f"\nSTEP 4 — Training scVI (max_epochs={max_epochs})")
    log.info(
        "  The ELBO (Evidence Lower BOund) is maximised during training.\n"
        "  Early stopping monitors validation ELBO with patience=20 epochs\n"
        "  to prevent overfitting."
    )
    plan_kwargs = {"lr": lr, "weight_decay": 1e-6}
    model.train(
        max_epochs=max_epochs,
        early_stopping=True,
        early_stopping_patience=20,
        early_stopping_monitor="elbo_validation",
        plan_kwargs=plan_kwargs,
        check_val_every_n_epoch=5,
    )
    plot_training_history(model.history, FIG_DIR / "scvi_training_history.pdf")

    # Save trained model weights for reproducibility
    MODEL_DIR.mkdir(parents=True, exist_ok=True)
    model.save(str(MODEL_DIR), overwrite=True)
    log.info(f"  Model saved → {MODEL_DIR.name}/")

    # ---- 5. Extract latent representation -------------------------------
    log.info("\nSTEP 5 — Extracting scVI latent embedding")
    log.info(
        "  The 30-dimensional latent space encodes biological cell identity\n"
        "  with batch effects modelled out.  This embedding is used for:\n"
        "    • Neighbour graph construction (KNN in latent space)\n"
        "    • UMAP visualization\n"
        "    • Leiden clustering"
    )
    adata.obsm["X_scVI"] = model.get_latent_representation()

    log.info("\nSTEP 5b — Computing batch-corrected normalized expression")
    log.info(
        "  scVI also produces a batch-corrected expression matrix by\n"
        "  decoding each cell through a 'reference batch' condition.\n"
        "  Stored in .layers['scvi_normalized'] for downstream differential\n"
        "  expression and pathway activity scoring."
    )
    adata.layers["scvi_normalized"] = model.get_normalized_expression(
        library_size=1e4
    )

    # ---- 6. Neighbour graph on latent space -----------------------------
    log.info("\nSTEP 6 — Building KNN graph on scVI latent space")
    log.info(
        "  n_neighbors=30: balances local and global structure. Larger\n"
        "  values produce smoother UMAP at the cost of local resolution."
    )
    sc.pp.neighbors(adata, use_rep="X_scVI", n_neighbors=30)

    # ---- 7. UMAP + Leiden clustering ------------------------------------
    log.info("\nSTEP 7 — UMAP embedding and Leiden clustering")
    sc.tl.umap(adata, min_dist=0.3)

    log.info(
        f"  Running Leiden clustering at resolutions: {leiden_resolutions}\n"
        "  WHY MULTIPLE RESOLUTIONS: Low resolution gives broad cell-type\n"
        "  clusters (useful for annotation); high resolution gives fine\n"
        "  subclusters within cone precursors (used for Aim 2 and Aim 3)."
    )
    for res in leiden_resolutions:
        sc.tl.leiden(adata, resolution=res, key_added=f"leiden_{res:.1f}")
        n_clusters = adata.obs[f"leiden_{res:.1f}"].nunique()
        log.info(f"  Resolution {res}: {n_clusters} clusters")

    plot_umap(
        adata, ["dataset", "sample_id"],
        "UMAP after scVI integration — batch labels",
        FIG_DIR / "umap_after_integration_dataset.pdf",
    )
    plot_umap(
        adata, ["leiden_0.5", "leiden_1.0"],
        "UMAP after scVI integration — Leiden clusters",
        FIG_DIR / "umap_after_integration_clusters.pdf",
    )

    # ---- 8. Integration quality (scib-metrics) --------------------------
    log.info("\nSTEP 8 — Evaluating integration quality (scib-metrics)")
    log.info(
        "  Computing batch correction vs biological conservation scores.\n"
        "  Target: overall score > 0.7 (Luecken et al. 2022)"
    )
    try:
        import scib
        metrics = scib.metrics.metrics(
            adata,
            adata_int=adata,
            batch_key="dataset",
            label_key="leiden_0.5",
            embed="X_scVI",
            cluster_key="leiden_0.5",
            organism="human",
            verbose=False,
        )
        metrics_df = pd.DataFrame(metrics).T
        metrics_df.to_csv(TAB_DIR / "scib_integration_metrics.csv")
        log.info(f"  scib metrics saved → {TAB_DIR / 'scib_integration_metrics.csv'}")
        log.info(f"  Overall score: {metrics_df.get('Overall Score', 'N/A')}")
    except ImportError:
        log.warning(
            "  scib not installed — skipping integration metrics.\n"
            "  Install with: pip install scib-metrics"
        )

    # ---- 9. Save --------------------------------------------------------
    log.info(f"\nSTEP 9 — Saving integrated atlas → {OUT_H5AD.name}")
    log.info(
        "  Contents:\n"
        "    .X                   : log-normalized expression\n"
        "    .layers['counts']    : raw UMI counts (for scVI re-training)\n"
        "    .layers['lognorm']   : log-normalized counts\n"
        "    .layers['scvi_norm'] : scVI batch-corrected expression\n"
        "    .obsm['X_scVI']      : 30-d scVI latent space\n"
        "    .obsm['X_umap']      : 2-d UMAP coordinates\n"
        "    .obs['leiden_*']     : Leiden cluster labels"
    )
    adata.write_h5ad(OUT_H5AD, compression="gzip")
    log.info("  Done.\n")
    return adata


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="scVI batch correction for RetinoblastomaAtlas",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--n-latent",   type=int,   default=30)
    p.add_argument("--n-layers",   type=int,   default=2)
    p.add_argument("--n-hidden",   type=int,   default=128)
    p.add_argument("--max-epochs", type=int,   default=400)
    p.add_argument("--lr",         type=float, default=1e-3)
    return p.parse_args()


if __name__ == "__main__":
    args = parse_args()
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    TAB_DIR.mkdir(parents=True, exist_ok=True)
    run_integration(
        n_latent=args.n_latent,
        n_layers=args.n_layers,
        n_hidden=args.n_hidden,
        max_epochs=args.max_epochs,
        lr=args.lr,
    )
